Drop table if exists Tag_table;
Drop table if exists Talk_fact_dim;
Drop table if exists Speaker;
Drop table if exists Talk_meta_data_dim
Drop table if exists User_ratings
Drop table if exists Linguistic_score_table

Create table Talk_fact_dim
	(talk_id	int not null primary key,
	talk_description nVarchar(max),
	talk_languages	int,
	title		nVarchar(1000) not null)

CREATE TABLE Talk_meta_data_dim(
    talk_id	int not null primary key,
    duration int,
    comment_num int;
    talk_event varchar(200),
    published_date Date,
    talk_url nvarchar(200),
    view_count int,
    film_date Date,
    WC int,
	main_speaker varchar(50) not null
	
)



CREATE TABLE Speaker(
    main_speaker varchar(50),
    speaker_occupation varchar(200))
)

CREATE TABLE User_ratings(
talk_id	int not null primary key,
persuasive int,
inspiring int,
unconvincing int,
applause int,
laughter int,
norm_persuasive float,
norm_inspiring float,
norm_unconvincing float,
)

CREATE TABLE Linguistic_score_table(
talk_id	int not null primary key,
Analytic float,
Clout float,
Authentic float,
Tone float,
WPS float,
Sixltr float,
Dic float,
function_words float,
pronoun float,
ppron float,
i float,
we float,
you float,
shehe float,
they float,
ipron float,
article float,
prep float,
auxverb float,
adverb float,
conj float,
negate float,
verb float,
adj float,
compare float,
interrog float,
number float,
quant float,
affect float,
posemo float,
negemo float,
anx float,
anger float,
sad float,
social float,
family float,
friend float,
female float,
male float,
cogproc float,
insight float,
cause float,
discrep float,
tentat float,
certain float,
differ float,
percept float,
see float,
hear float,
feel float,
bio float,
body float,
health float,
sexual float,
ingest float,
drives float,
affiliation float,
achieve float,
power_words float,
reward float,
risk float,
focuspast float,
focuspresent float,
focusfuture float,
relativ float,
motion float,
space_var float,
time_var float,
work float,
leisure float,
home float,
money_words float,
relig float,
death float,
informal float,
swear float,
netspeak float,
assent float,
nonflu float,
filler float,
AllPunc float,
Period_words float,
Comma float,
Colon float,
SemiC float,
QMark float,
Exclam float,
Dash float,
Quote float,
Apostro float,
Parenth float,
OtherP float,
Moral float,
HarmVirtue float,
HarmVice float,
FairnessVirtue float,
FairnessVice float,
IngroupVirtue float,
IngroupVice float,
AuthorityVirtue float,
AuthorityVice float,
PurityVirtue float,
PurityVice float,
MoralityGeneral float,
affect_1h float,
posemo_1h float,
negemo_1h float,
anx_1h float,
anger_1h float,
sad_1h float,
affect_2h float,
posemo_2h float,
negemo_2h float,
anx_2h float,
anger_2h float,
sad_2h float,
affect_1q float,
posemo_1q float,
negemo_1q float,
anx_1q float,
anger_1q float,
sad_1q float,
affect_2q float,
posemo_2q float,
negemo_2q float,
anx_2q float,
anger_2q float,
sad_2q float,
affect_3q float,
posemo_3q float,
negemo_3q float,
anx_3q float,
anger_3q float,
sad_3q float,
affect_4q float,
posemo_4q float,
negemo_4q float,
anx_4q float,
anger_4q float,
sad_4q float,
posemo_change_h float,
negemo_change_h float,
affect_change_h float,
posemo_change_q float,
negemo_change_q float,
affect_change_q float,
published_year float,
Harm float,
Fairness float,
Purity float,
Ingroup float,
Authority float
)

Create table Tag_table
	(talk_id	int not null primary key references Talk_fact_dim(talk_id),
	 tag		varchar(30))


Alter table Talk_meta_data_dim
ADD FOREIGN KEY (main_speaker) REFERENCES Speaker(main_speaker);

Create table Related_talks_id
	(talk_id int not null,
	related_id int not null
	);